# render.yaml
services:
  - type: web
    name: hospital-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.frftfqgthkrpkmjzzogo:Hunter223/@aws-0-eu-central-1.pooler.supabase.com:6543/postgres
      - key: SECRET_KEY
        value: mysecretkey
      - key: JWT_SECRET
        value: myjwtsecret
