"""Update Patient model to display doctor name

Revision ID: 51408197c0e6
Revises: a477f83061e2
Create Date: 2025-03-22 14:40:51.085271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51408197c0e6'
down_revision = 'a477f83061e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_patients_doctor_id',  # Explicitly name the foreign key constraint
            'users',  # Referenced table
            ['doctor_id'],  # Column in this table
            ['id']  # Column in the referenced table
        )
        batch_op.drop_column('doctor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_patients_doctor_id', type_='foreignkey')  # Use the correct constraint name
        batch_op.drop_column('doctor_id')

    # ### end Alembic commands ###
