"""Update Patient model

Revision ID: a477f83061e2
Revises: 16ed0cfe1353
Create Date: 2025-03-20 13:26:38.321296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a477f83061e2'
down_revision = '16ed0cfe1353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blood_group', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('chronic_conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('doctor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('image_path')
        batch_op.drop_column('doctor')
        batch_op.drop_column('chronic_conditions')
        batch_op.drop_column('allergies')
        batch_op.drop_column('blood_group')

    # ### end Alembic commands ###
