"""initial migration

Revision ID: a92a971af624
Revises: 0977c4c28c4a
Create Date: 2025-04-12 14:43:35.760925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a92a971af624'
down_revision = '0977c4c28c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("medical_records", schema=None) as batch_op:
        batch_op.drop_column("units_prescribed")
        batch_op.add_column(sa.Column("units_prescribed", postgresql.JSON(astext_type=sa.Text()), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_records', schema=None) as batch_op:
        batch_op.alter_column('units_prescribed',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
